set(lslsources
        src/api_config.cpp
        src/api_config.h
        src/api_types.hpp
        src/cancellable_streambuf.h
        src/cancellation.h
        src/cancellation.cpp
        src/common.cpp
        src/common.h
        src/consumer_queue.cpp
        src/consumer_queue.h
        src/data_receiver.cpp
        src/data_receiver.h
        src/forward.h
        src/info_receiver.cpp
        src/info_receiver.h
        src/inlet_connection.cpp
        src/inlet_connection.h
        src/lsl_resolver_c.cpp
        src/lsl_inlet_c.cpp
        src/lsl_outlet_c.cpp
        src/lsl_streaminfo_c.cpp
        src/lsl_xml_element_c.cpp
        src/netinterfaces.h
        src/netinterfaces.cpp
        src/portable_archive/portable_archive_exception.hpp
        src/portable_archive/portable_archive_includes.hpp
        src/portable_archive/portable_iarchive.hpp
        src/portable_archive/portable_oarchive.hpp
        src/resolver_impl.cpp
        src/resolver_impl.h
        src/resolve_attempt_udp.cpp
        src/resolve_attempt_udp.h
        src/sample.cpp
        src/sample.h
        src/send_buffer.cpp
        src/send_buffer.h
        src/socket_utils.cpp
        src/socket_utils.h
        src/stream_info_impl.cpp
        src/stream_info_impl.h
        src/stream_inlet_impl.h
        src/stream_outlet_impl.cpp
        src/stream_outlet_impl.h
        src/tcp_server.cpp
        src/tcp_server.h
        src/time_postprocessor.cpp
        src/time_postprocessor.h
        src/time_receiver.cpp
        src/time_receiver.h
        src/udp_server.cpp
        src/udp_server.h
        src/util/cast.hpp
        src/util/cast.cpp
        src/util/endian.cpp
        src/util/endian.hpp
        src/util/inireader.hpp
        src/util/inireader.cpp
        src/util/strfuns.hpp
        src/util/strfuns.cpp
        src/util/uuid.hpp
        thirdparty/loguru/loguru.cpp
        $<$<BOOL:${LSL_LEGACY_CPP_ABI}>:src/legacy/legacy_abi.cpp src/legacy/legacy_abi.h>
)
set(lslheaders
        include/lsl_c.h
        include/lsl_cpp.h
        include/lsl/common.h
        include/lsl/inlet.h
        include/lsl/outlet.h
        include/lsl/resolver.h
        include/lsl/streaminfo.h
        include/lsl/types.h
        include/lsl/xml.h
)