# Build utilities (only when liblsl is the top-level project)
if(CMAKE_SOURCE_DIR STREQUAL PROJECT_SOURCE_DIR)
    include(GNUInstallDirs)

    add_executable(lslver testing/lslver.c)
    target_link_libraries(lslver PRIVATE lsl)
    set_target_properties(lslver PROPERTIES FOLDER "liblsl")
    if(LSL_INSTALL AND NOT IOS)
        install(TARGETS lslver RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
    endif()

    if(NOT WIN32 AND LSL_TOOLS)
        add_executable(blackhole testing/blackhole.cpp)
        target_link_libraries(blackhole PRIVATE Threads::Threads)
        target_include_directories(blackhole PRIVATE "thirdparty/asio/")
        set_target_properties(blackhole PROPERTIES FOLDER "liblsl")
        if(LSL_INSTALL AND NOT IOS)
            install(TARGETS blackhole RUNTIME DESTINATION "${CMAKE_INSTALL_BINDIR}")
        endif()
    endif()
endif()
