name: Android

on:
  push:
    branches: ['androidci']
    paths_ignore: ['docs/**', '.travis.yml']
  workflow_dispatch:
    inputs:
      cmakeextra:
        description: 'Extra CMake options'
        required: false
        default: ''

defaults:
  run:
    shell: bash


jobs:
  build:
    name: ${{ matrix.config.arch }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        config:
        - {arch: "x86"}
        - {arch: "armeabi-v7a" }
        - {arch: "arm64-v8a"}

    steps:
    - uses: actions/checkout@v2

    - name: Configure CMake
      run: |
           cmake --version
           cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=${PWD}/install \
                -DLSL_UNITTESTS=ON \
                -DCPACK_PACKAGE_DIRECTORY=${PWD}/package \
                -Dlslgitrevision=${{ github.sha }} \
                -Dlslgitbranch=${{ github.ref }} \
                -DCMAKE_SYSTEM_NAME=Android \
                -DCMAKE_SYSTEM_VERSION=30 \
                -DCMAKE_ANDROID_ARCH_ABI=${{ matrix.config.arch }}
                ${{ matrix.config.cmake_extra }} 
            echo ${PWD}
    - name: make
      run: cmake --build build --target install --config Release -j
    - name: upload install dir
      uses: actions/upload-artifact@master
      with:
        name: build-android-${{ matrix.config.arch }}
        path: install

