name: MinGW Windows Builds

on:
  push:
    branches: ['*']
    paths:
      - 'src'
      - 'include'
      - 'cmake'
#      - '!docs/**'
#      - '!.github/**'
      - '.github/workflows/mingw_static.yml'
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    name: MinGW ${{ matrix.msys }} ${{ matrix.lib_type }}
    strategy:
      matrix:
        include:
          - { runs_on: windows-latest, msys: ucrt64,     lib_type: DLL }
          - { runs_on: windows-11-arm, msys: clangarm64, lib_type: DLL }
          - { runs_on: windows-latest, msys: ucrt64,     lib_type: static }
          - { runs_on: windows-11-arm, msys: clangarm64, lib_type: static }
    runs-on: ${{ matrix.runs_on }}
    defaults:
      run:
        shell: 'msys2 {0}'
    steps:
    - uses: actions/checkout@v5
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{matrix.msys}}
        update: true
        cache: true
        install: >-
            git
            make
        pacboy: >-
            toolchain:p
            cmake:p
            ninja:p
    - name: Configure CMake
      run: |
           cmake --version
           cmake -S . -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_INSTALL_PREFIX=${PWD}/install \
                -DLSL_UNITTESTS=ON \
                -DLSL_BUILD_STATIC=${{ matrix.lib_type == 'DLL' && 'OFF' || 'ON' }} \
                -Dlslgitrevision=${{ github.sha }} \
                -Dlslgitbranch=${{ github.ref }} \
                -DLSL_OPTIMIZATIONS=OFF \
                -G Ninja

    - name: make
      run: cmake --build build --target install --config Release -j --verbose
  
    - name: upload install dir
      uses: actions/upload-artifact@master
      with:
        name: mingw_${{ matrix.msys }}_${{ matrix.lib_type }}_artifacts
        path: install

    - name: unit tests (internal functions)
      run: 'install/bin/lsl_test_internal --order rand --wait-for-keypress never --durations yes'
      timeout-minutes: 5
      if: matrix.msys == 'ucrt64' # skip experimental clangarm64 builds
    
    - name: unit tests (exported functions)
      run: install/bin/lsl_test_exported --wait-for-keypress never --durations yes
      timeout-minutes: 5
      if: matrix.msys == 'ucrt64' # skip experimental clangarm64 builds
